name: main

on:
  push:
      branches:
        - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
         - uses: actions/checkout@v2

         - name: set_ssh
           uses: appleboy/ssh-action@v0.1.10
           with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                script: |
                  cd shop-on-the-couch
                  docker compose -f .docker/docker-compose.prod.yml stop
                  git checkout -B main
                  git reset --hard master
                  git pull
                  cd frontend
                  npm run prod_build
                  cd ..
                  docker compose -f .docker/docker-compose.prod.yml build
                  docker compose -f .docker/docker-compose.prod.yml up --detach
                  docker compose -f .docker/docker-compose.prod.yml exec backend python manage.py collectstatic --noinput
                  docker system prune -f